apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-pxyd
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0059-tenant/tkrw-pr712-0075-0059-app/devfile-sample-pxyd@sha256:342c9bdbf1c9e4f9934c3227060bdc0527a74da587b4055ce821223f9ca874ed
        name: my-nodejs
        resources: {}
status: {}
